// Auto-generated from DANE municipalities seed migration
// Source: DANE (Departamento Administrativo Nacional de Estadística)
// Total municipalities: 1112

export interface DaneEntry {
  municipality: string;
  department: string;
  daneCode: string;
}

export interface DaneLookupResult extends DaneEntry {
  source: string;
}

const DANE_ENTRIES: DaneEntry[] = [
  { municipality: 'Leticia', department: 'Amazonas', daneCode: '91001' },
  { municipality: 'El Encanto', department: 'Amazonas', daneCode: '91263' },
  { municipality: 'La Chorrera', department: 'Amazonas', daneCode: '91405' },
  { municipality: 'La Pedrera', department: 'Amazonas', daneCode: '91407' },
  { municipality: 'La Victoria', department: 'Amazonas', daneCode: '91430' },
  { municipality: 'Mirití-Paraná', department: 'Amazonas', daneCode: '91460' },
  { municipality: 'Puerto Alegría', department: 'Amazonas', daneCode: '91530' },
  { municipality: 'Puerto Arica', department: 'Amazonas', daneCode: '91536' },
  { municipality: 'Puerto Nariño', department: 'Amazonas', daneCode: '91540' },
  { municipality: 'Puerto Santander', department: 'Amazonas', daneCode: '91669' },
  { municipality: 'Tarapacá', department: 'Amazonas', daneCode: '91798' },
  { municipality: 'Medellín', department: 'Antioquia', daneCode: '05001' },
  { municipality: 'Abejorral', department: 'Antioquia', daneCode: '05002' },
  { municipality: 'Abriaquí', department: 'Antioquia', daneCode: '05004' },
  { municipality: 'Alejandría', department: 'Antioquia', daneCode: '05021' },
  { municipality: 'Amagá', department: 'Antioquia', daneCode: '05030' },
  { municipality: 'Amalfi', department: 'Antioquia', daneCode: '05031' },
  { municipality: 'Andes', department: 'Antioquia', daneCode: '05034' },
  { municipality: 'Angelópolis', department: 'Antioquia', daneCode: '05036' },
  { municipality: 'Angostura', department: 'Antioquia', daneCode: '05038' },
  { municipality: 'Anorí', department: 'Antioquia', daneCode: '05040' },
  { municipality: 'Anzá', department: 'Antioquia', daneCode: '05044' },
  { municipality: 'Apartadó', department: 'Antioquia', daneCode: '05045' },
  { municipality: 'Arboletes', department: 'Antioquia', daneCode: '05051' },
  { municipality: 'Argelia', department: 'Antioquia', daneCode: '05055' },
  { municipality: 'Armenia', department: 'Antioquia', daneCode: '05059' },
  { municipality: 'Barbosa', department: 'Antioquia', daneCode: '05079' },
  { municipality: 'Bello', department: 'Antioquia', daneCode: '05088' },
  { municipality: 'Belmira', department: 'Antioquia', daneCode: '05086' },
  { municipality: 'Betania', department: 'Antioquia', daneCode: '05091' },
  { municipality: 'Betulia', department: 'Antioquia', daneCode: '05093' },
  { municipality: 'Briceño', department: 'Antioquia', daneCode: '05107' },
  { municipality: 'Buriticá', department: 'Antioquia', daneCode: '05113' },
  { municipality: 'Cáceres', department: 'Antioquia', daneCode: '05120' },
  { municipality: 'Caicedo', department: 'Antioquia', daneCode: '05125' },
  { municipality: 'Caldas', department: 'Antioquia', daneCode: '05129' },
  { municipality: 'Campamento', department: 'Antioquia', daneCode: '05134' },
  { municipality: 'Cañasgordas', department: 'Antioquia', daneCode: '05138' },
  { municipality: 'Caracolí', department: 'Antioquia', daneCode: '05142' },
  { municipality: 'Caramanta', department: 'Antioquia', daneCode: '05145' },
  { municipality: 'Carepa', department: 'Antioquia', daneCode: '05147' },
  { municipality: 'Carolina del Príncipe', department: 'Antioquia', daneCode: '05150' },
  { municipality: 'Caucasia', department: 'Antioquia', daneCode: '05154' },
  { municipality: 'Chigorodó', department: 'Antioquia', daneCode: '05172' },
  { municipality: 'Cisneros', department: 'Antioquia', daneCode: '05190' },
  { municipality: 'Cocorná', department: 'Antioquia', daneCode: '05197' },
  { municipality: 'Concepción', department: 'Antioquia', daneCode: '05206' },
  { municipality: 'Concordia', department: 'Antioquia', daneCode: '05209' },
  { municipality: 'Copacabana', department: 'Antioquia', daneCode: '05212' },
  { municipality: 'Dabeiba', department: 'Antioquia', daneCode: '05234' },
  { municipality: 'Donmatías', department: 'Antioquia', daneCode: '05237' },
  { municipality: 'Ebéjico', department: 'Antioquia', daneCode: '05240' },
  { municipality: 'El Bagre', department: 'Antioquia', daneCode: '05250' },
  { municipality: 'El Carmen de Viboral', department: 'Antioquia', daneCode: '05148' },
  { municipality: 'El Santuario', department: 'Antioquia', daneCode: '05697' },
  { municipality: 'Entrerríos', department: 'Antioquia', daneCode: '05264' },
  { municipality: 'Envigado', department: 'Antioquia', daneCode: '05266' },
  { municipality: 'Fredonia', department: 'Antioquia', daneCode: '05282' },
  { municipality: 'Frontino', department: 'Antioquia', daneCode: '05284' },
  { municipality: 'Giraldo', department: 'Antioquia', daneCode: '05306' },
  { municipality: 'Girardota', department: 'Antioquia', daneCode: '05308' },
  { municipality: 'Gómez Plata', department: 'Antioquia', daneCode: '05310' },
  { municipality: 'Granada', department: 'Antioquia', daneCode: '05313' },
  { municipality: 'Guadalupe', department: 'Antioquia', daneCode: '05315' },
  { municipality: 'Guarne', department: 'Antioquia', daneCode: '05318' },
  { municipality: 'Guatapé', department: 'Antioquia', daneCode: '05321' },
  { municipality: 'Heliconia', department: 'Antioquia', daneCode: '05347' },
  { municipality: 'Hispania', department: 'Antioquia', daneCode: '05353' },
  { municipality: 'Itagüí', department: 'Antioquia', daneCode: '05360' },
  { municipality: 'Ituango', department: 'Antioquia', daneCode: '05361' },
  { municipality: 'Jardín', department: 'Antioquia', daneCode: '05364' },
  { municipality: 'Jericó', department: 'Antioquia', daneCode: '05368' },
  { municipality: 'La Ceja', department: 'Antioquia', daneCode: '05376' },
  { municipality: 'La Estrella', department: 'Antioquia', daneCode: '05380' },
  { municipality: 'La Pintada', department: 'Antioquia', daneCode: '05390' },
  { municipality: 'La Unión', department: 'Antioquia', daneCode: '05400' },
  { municipality: 'Liborina', department: 'Antioquia', daneCode: '05411' },
  { municipality: 'Maceo', department: 'Antioquia', daneCode: '05425' },
  { municipality: 'Marinilla', department: 'Antioquia', daneCode: '05440' },
  { municipality: 'Montebello', department: 'Antioquia', daneCode: '05467' },
  { municipality: 'Murindó', department: 'Antioquia', daneCode: '05475' },
  { municipality: 'Mutatá', department: 'Antioquia', daneCode: '05480' },
  { municipality: 'Nariño', department: 'Antioquia', daneCode: '05483' },
  { municipality: 'Necoclí', department: 'Antioquia', daneCode: '05490' },
  { municipality: 'Nechí', department: 'Antioquia', daneCode: '05495' },
  { municipality: 'Olaya', department: 'Antioquia', daneCode: '05501' },
  { municipality: 'El Peñol', department: 'Antioquia', daneCode: '05541' },
  { municipality: 'Peque', department: 'Antioquia', daneCode: '05543' },
  { municipality: 'Pueblorrico', department: 'Antioquia', daneCode: '05576' },
  { municipality: 'Puerto Berrío', department: 'Antioquia', daneCode: '05579' },
  { municipality: 'Puerto Nare', department: 'Antioquia', daneCode: '05585' },
  { municipality: 'Puerto Triunfo', department: 'Antioquia', daneCode: '05591' },
  { municipality: 'Remedios', department: 'Antioquia', daneCode: '05604' },
  { municipality: 'El Retiro', department: 'Antioquia', daneCode: '05607' },
  { municipality: 'Rionegro', department: 'Antioquia', daneCode: '05615' },
  { municipality: 'Sabanalarga', department: 'Antioquia', daneCode: '05628' },
  { municipality: 'Sabaneta', department: 'Antioquia', daneCode: '05631' },
  { municipality: 'Salgar', department: 'Antioquia', daneCode: '05642' },
  { municipality: 'San Andrés de Cuerquia', department: 'Antioquia', daneCode: '05647' },
  { municipality: 'San Carlos', department: 'Antioquia', daneCode: '05649' },
  { municipality: 'San Francisco', department: 'Antioquia', daneCode: '05652' },
  { municipality: 'San Jerónimo', department: 'Antioquia', daneCode: '05656' },
  { municipality: 'San José de la Montaña', department: 'Antioquia', daneCode: '05658' },
  { municipality: 'San Juan de Urabá', department: 'Antioquia', daneCode: '05659' },
  { municipality: 'San Luis', department: 'Antioquia', daneCode: '05660' },
  { municipality: 'San Pedro de los Milagros', department: 'Antioquia', daneCode: '05664' },
  { municipality: 'San Pedro de Urabá', department: 'Antioquia', daneCode: '05665' },
  { municipality: 'San Rafael', department: 'Antioquia', daneCode: '05667' },
  { municipality: 'San Roque', department: 'Antioquia', daneCode: '05670' },
  { municipality: 'San Vicente Ferrer', department: 'Antioquia', daneCode: '05674' },
  { municipality: 'Santa Bárbara', department: 'Antioquia', daneCode: '05679' },
  { municipality: 'Santa Rosa de Osos', department: 'Antioquia', daneCode: '05686' },
  { municipality: 'Santo Domingo', department: 'Antioquia', daneCode: '05690' },
  { municipality: 'Segovia', department: 'Antioquia', daneCode: '05736' },
  { municipality: 'Sonsón', department: 'Antioquia', daneCode: '05756' },
  { municipality: 'Sopetrán', department: 'Antioquia', daneCode: '05761' },
  { municipality: 'Támesis', department: 'Antioquia', daneCode: '05789' },
  { municipality: 'Tarazá', department: 'Antioquia', daneCode: '05790' },
  { municipality: 'Tarso', department: 'Antioquia', daneCode: '05792' },
  { municipality: 'Titiribí', department: 'Antioquia', daneCode: '05809' },
  { municipality: 'Toledo', department: 'Antioquia', daneCode: '05819' },
  { municipality: 'Turbo', department: 'Antioquia', daneCode: '05837' },
  { municipality: 'Uramita', department: 'Antioquia', daneCode: '05842' },
  { municipality: 'Urrao', department: 'Antioquia', daneCode: '05847' },
  { municipality: 'Valdivia', department: 'Antioquia', daneCode: '05854' },
  { municipality: 'Valparaíso', department: 'Antioquia', daneCode: '05856' },
  { municipality: 'Vegachí', department: 'Antioquia', daneCode: '05858' },
  { municipality: 'Venecia', department: 'Antioquia', daneCode: '05861' },
  { municipality: 'Vigía del Fuerte', department: 'Antioquia', daneCode: '05873' },
  { municipality: 'Yalí', department: 'Antioquia', daneCode: '05885' },
  { municipality: 'Yarumal', department: 'Antioquia', daneCode: '05887' },
  { municipality: 'Yolombó', department: 'Antioquia', daneCode: '05890' },
  { municipality: 'Yondó', department: 'Antioquia', daneCode: '05893' },
  { municipality: 'Zaragoza', department: 'Antioquia', daneCode: '05895' },
  { municipality: 'Arauca', department: 'Arauca', daneCode: '81001' },
  { municipality: 'Arauquita', department: 'Arauca', daneCode: '81065' },
  { municipality: 'Cravo Norte', department: 'Arauca', daneCode: '81220' },
  { municipality: 'Fortul', department: 'Arauca', daneCode: '81300' },
  { municipality: 'Puerto Rondón', department: 'Arauca', daneCode: '81591' },
  { municipality: 'Saravena', department: 'Arauca', daneCode: '81736' },
  { municipality: 'Tame', department: 'Arauca', daneCode: '81794' },
  { municipality: 'Barranquilla', department: 'Atlántico', daneCode: '08001' },
  { municipality: 'Baranoa', department: 'Atlántico', daneCode: '08078' },
  { municipality: 'Campo de la Cruz', department: 'Atlántico', daneCode: '08137' },
  { municipality: 'Candelaria', department: 'Atlántico', daneCode: '08141' },
  { municipality: 'Galapa', department: 'Atlántico', daneCode: '08296' },
  { municipality: 'Juan de Acosta', department: 'Atlántico', daneCode: '08372' },
  { municipality: 'Luruaco', department: 'Atlántico', daneCode: '08421' },
  { municipality: 'Malambo', department: 'Atlántico', daneCode: '08433' },
  { municipality: 'Manatí', department: 'Atlántico', daneCode: '08436' },
  { municipality: 'Palmar de Varela', department: 'Atlántico', daneCode: '08520' },
  { municipality: 'Piojó', department: 'Atlántico', daneCode: '08549' },
  { municipality: 'Polonuevo', department: 'Atlántico', daneCode: '08558' },
  { municipality: 'Ponedera', department: 'Atlántico', daneCode: '08560' },
  { municipality: 'Puerto Colombia', department: 'Atlántico', daneCode: '08573' },
  { municipality: 'Repelón', department: 'Atlántico', daneCode: '08606' },
  { municipality: 'Sabanagrande', department: 'Atlántico', daneCode: '08634' },
  { municipality: 'Sabanalarga', department: 'Atlántico', daneCode: '08638' },
  { municipality: 'Santa Lucía', department: 'Atlántico', daneCode: '08675' },
  { municipality: 'Santo Tomás', department: 'Atlántico', daneCode: '08685' },
  { municipality: 'Soledad', department: 'Atlántico', daneCode: '08758' },
  { municipality: 'Suan', department: 'Atlántico', daneCode: '08770' },
  { municipality: 'Tubará', department: 'Atlántico', daneCode: '08832' },
  { municipality: 'Usiacurí', department: 'Atlántico', daneCode: '08849' },
  { municipality: 'Bogotá D.C.', department: 'Bogotá D.C.', daneCode: '11001' },
  { municipality: 'Bogotá', department: 'Bogotá D.C.', daneCode: '11001' },
  { municipality: 'Cartagena de Indias', department: 'Bolívar', daneCode: '13001' },
  { municipality: 'Cartagena', department: 'Bolívar', daneCode: '13001' },
  { municipality: 'Achí', department: 'Bolívar', daneCode: '13006' },
  { municipality: 'Altos del Rosario', department: 'Bolívar', daneCode: '13030' },
  { municipality: 'Arenal', department: 'Bolívar', daneCode: '13042' },
  { municipality: 'Arjona', department: 'Bolívar', daneCode: '13052' },
  { municipality: 'Arroyohondo', department: 'Bolívar', daneCode: '13062' },
  { municipality: 'Barranco de Loba', department: 'Bolívar', daneCode: '13074' },
  { municipality: 'Calamar', department: 'Bolívar', daneCode: '13140' },
  { municipality: 'Cantagallo', department: 'Bolívar', daneCode: '13160' },
  { municipality: 'Cicuco', department: 'Bolívar', daneCode: '13188' },
  { municipality: 'Clemencia', department: 'Bolívar', daneCode: '13222' },
  { municipality: 'Córdoba', department: 'Bolívar', daneCode: '13212' },
  { municipality: 'El Carmen de Bolívar', department: 'Bolívar', daneCode: '13244' },
  { municipality: 'El Guamo', department: 'Bolívar', daneCode: '13248' },
  { municipality: 'El Peñón', department: 'Bolívar', daneCode: '13268' },
  { municipality: 'Hatillo de Loba', department: 'Bolívar', daneCode: '13300' },
  { municipality: 'Magangué', department: 'Bolívar', daneCode: '13430' },
  { municipality: 'Mahates', department: 'Bolívar', daneCode: '13433' },
  { municipality: 'Margarita', department: 'Bolívar', daneCode: '13440' },
  { municipality: 'María la Baja', department: 'Bolívar', daneCode: '13442' },
  { municipality: 'Montecristo', department: 'Bolívar', daneCode: '13458' },
  { municipality: 'Morales', department: 'Bolívar', daneCode: '13468' },
  { municipality: 'Norosí', department: 'Bolívar', daneCode: '13490' },
  { municipality: 'Pinillos', department: 'Bolívar', daneCode: '13549' },
  { municipality: 'Regidor', department: 'Bolívar', daneCode: '13580' },
  { municipality: 'Río Viejo', department: 'Bolívar', daneCode: '13600' },
  { municipality: 'San Cristóbal', department: 'Bolívar', daneCode: '13620' },
  { municipality: 'San Estanislao', department: 'Bolívar', daneCode: '13647' },
  { municipality: 'San Fernando', department: 'Bolívar', daneCode: '13650' },
  { municipality: 'San Jacinto', department: 'Bolívar', daneCode: '13654' },
  { municipality: 'San Jacinto del Cauca', department: 'Bolívar', daneCode: '13655' },
  { municipality: 'San Juan Nepomuceno', department: 'Bolívar', daneCode: '13657' },
  { municipality: 'San Martín de Loba', department: 'Bolívar', daneCode: '13667' },
  { municipality: 'San Pablo', department: 'Bolívar', daneCode: '13670' },
  { municipality: 'Santa Catalina', department: 'Bolívar', daneCode: '13673' },
  { municipality: 'Santa Rosa', department: 'Bolívar', daneCode: '13683' },
  { municipality: 'Santa Rosa del Sur', department: 'Bolívar', daneCode: '13688' },
  { municipality: 'Simití', department: 'Bolívar', daneCode: '13744' },
  { municipality: 'Soplaviento', department: 'Bolívar', daneCode: '13760' },
  { municipality: 'Talaigua Nuevo', department: 'Bolívar', daneCode: '13780' },
  { municipality: 'Tiquisio', department: 'Bolívar', daneCode: '13810' },
  { municipality: 'Turbaco', department: 'Bolívar', daneCode: '13836' },
  { municipality: 'Turbaná', department: 'Bolívar', daneCode: '13838' },
  { municipality: 'Villanueva', department: 'Bolívar', daneCode: '13873' },
  { municipality: 'Zambrano', department: 'Bolívar', daneCode: '13894' },
  { municipality: 'Tunja', department: 'Boyacá', daneCode: '15001' },
  { municipality: 'Almeida', department: 'Boyacá', daneCode: '15022' },
  { municipality: 'Aquitania', department: 'Boyacá', daneCode: '15047' },
  { municipality: 'Arcabuco', department: 'Boyacá', daneCode: '15051' },
  { municipality: 'Belén', department: 'Boyacá', daneCode: '15087' },
  { municipality: 'Berbeo', department: 'Boyacá', daneCode: '15090' },
  { municipality: 'Betéitiva', department: 'Boyacá', daneCode: '15092' },
  { municipality: 'Boavita', department: 'Boyacá', daneCode: '15097' },
  { municipality: 'Boyacá', department: 'Boyacá', daneCode: '15104' },
  { municipality: 'Briceño', department: 'Boyacá', daneCode: '15106' },
  { municipality: 'Buenavista', department: 'Boyacá', daneCode: '15109' },
  { municipality: 'Busbanzá', department: 'Boyacá', daneCode: '15114' },
  { municipality: 'Caldas', department: 'Boyacá', daneCode: '15131' },
  { municipality: 'Campohermoso', department: 'Boyacá', daneCode: '15135' },
  { municipality: 'Cerinza', department: 'Boyacá', daneCode: '15162' },
  { municipality: 'Chinavita', department: 'Boyacá', daneCode: '15172' },
  { municipality: 'Chiquinquirá', department: 'Boyacá', daneCode: '15176' },
  { municipality: 'Chiscas', department: 'Boyacá', daneCode: '15180' },
  { municipality: 'Chita', department: 'Boyacá', daneCode: '15183' },
  { municipality: 'Chitaraque', department: 'Boyacá', daneCode: '15185' },
  { municipality: 'Chivatá', department: 'Boyacá', daneCode: '15187' },
  { municipality: 'Chivor', department: 'Boyacá', daneCode: '15236' },
  { municipality: 'Ciénega', department: 'Boyacá', daneCode: '15189' },
  { municipality: 'Cómbita', department: 'Boyacá', daneCode: '15204' },
  { municipality: 'Coper', department: 'Boyacá', daneCode: '15212' },
  { municipality: 'Corrales', department: 'Boyacá', daneCode: '15215' },
  { municipality: 'Covarachía', department: 'Boyacá', daneCode: '15218' },
  { municipality: 'Cubará', department: 'Boyacá', daneCode: '15223' },
  { municipality: 'Cucaita', department: 'Boyacá', daneCode: '15224' },
  { municipality: 'Cuítiva', department: 'Boyacá', daneCode: '15226' },
  { municipality: 'Duitama', department: 'Boyacá', daneCode: '15238' },
  { municipality: 'El Cocuy', department: 'Boyacá', daneCode: '15244' },
  { municipality: 'El Espino', department: 'Boyacá', daneCode: '15248' },
  { municipality: 'Firavitoba', department: 'Boyacá', daneCode: '15272' },
  { municipality: 'Floresta', department: 'Boyacá', daneCode: '15276' },
  { municipality: 'Gachantivá', department: 'Boyacá', daneCode: '15293' },
  { municipality: 'Gámeza', department: 'Boyacá', daneCode: '15296' },
  { municipality: 'Garagoa', department: 'Boyacá', daneCode: '15299' },
  { municipality: 'Guacamayas', department: 'Boyacá', daneCode: '15317' },
  { municipality: 'Guateque', department: 'Boyacá', daneCode: '15322' },
  { municipality: 'Guayatá', department: 'Boyacá', daneCode: '15325' },
  { municipality: 'Güicán de la Sierra', department: 'Boyacá', daneCode: '15332' },
  { municipality: 'Iza', department: 'Boyacá', daneCode: '15362' },
  { municipality: 'Jenesano', department: 'Boyacá', daneCode: '15367' },
  { municipality: 'Jericó', department: 'Boyacá', daneCode: '15368' },
  { municipality: 'La Capilla', department: 'Boyacá', daneCode: '15380' },
  { municipality: 'La Uvita', department: 'Boyacá', daneCode: '15403' },
  { municipality: 'La Victoria', department: 'Boyacá', daneCode: '15401' },
  { municipality: 'Labranzagrande', department: 'Boyacá', daneCode: '15377' },
  { municipality: 'Macanal', department: 'Boyacá', daneCode: '15425' },
  { municipality: 'Maripí', department: 'Boyacá', daneCode: '15442' },
  { municipality: 'Miraflores', department: 'Boyacá', daneCode: '15455' },
  { municipality: 'Mongua', department: 'Boyacá', daneCode: '15464' },
  { municipality: 'Monguí', department: 'Boyacá', daneCode: '15466' },
  { municipality: 'Moniquirá', department: 'Boyacá', daneCode: '15469' },
  { municipality: 'Motavita', department: 'Boyacá', daneCode: '15476' },
  { municipality: 'Muzo', department: 'Boyacá', daneCode: '15480' },
  { municipality: 'Nobsa', department: 'Boyacá', daneCode: '15491' },
  { municipality: 'Nuevo Colón', department: 'Boyacá', daneCode: '15494' },
  { municipality: 'Oicatá', department: 'Boyacá', daneCode: '15500' },
  { municipality: 'Otanche', department: 'Boyacá', daneCode: '15507' },
  { municipality: 'Pachavita', department: 'Boyacá', daneCode: '15511' },
  { municipality: 'Páez', department: 'Boyacá', daneCode: '15514' },
  { municipality: 'Paipa', department: 'Boyacá', daneCode: '15516' },
  { municipality: 'Pajarito', department: 'Boyacá', daneCode: '15518' },
  { municipality: 'Panqueba', department: 'Boyacá', daneCode: '15522' },
  { municipality: 'Pauna', department: 'Boyacá', daneCode: '15531' },
  { municipality: 'Paya', department: 'Boyacá', daneCode: '15533' },
  { municipality: 'Paz de Río', department: 'Boyacá', daneCode: '15537' },
  { municipality: 'Pesca', department: 'Boyacá', daneCode: '15542' },
  { municipality: 'Pisba', department: 'Boyacá', daneCode: '15550' },
  { municipality: 'Puerto Boyacá', department: 'Boyacá', daneCode: '15572' },
  { municipality: 'Quípama', department: 'Boyacá', daneCode: '15580' },
  { municipality: 'Ramiriquí', department: 'Boyacá', daneCode: '15599' },
  { municipality: 'Ráquira', department: 'Boyacá', daneCode: '15600' },
  { municipality: 'Rondón', department: 'Boyacá', daneCode: '15621' },
  { municipality: 'Saboyá', department: 'Boyacá', daneCode: '15632' },
  { municipality: 'Sáchica', department: 'Boyacá', daneCode: '15638' },
  { municipality: 'Samacá', department: 'Boyacá', daneCode: '15646' },
  { municipality: 'San Eduardo', department: 'Boyacá', daneCode: '15660' },
  { municipality: 'San José de Pare', department: 'Boyacá', daneCode: '15664' },
  { municipality: 'San Luis de Gaceno', department: 'Boyacá', daneCode: '15667' },
  { municipality: 'San Mateo', department: 'Boyacá', daneCode: '15673' },
  { municipality: 'San Miguel de Sema', department: 'Boyacá', daneCode: '15676' },
  { municipality: 'San Pablo de Borbur', department: 'Boyacá', daneCode: '15681' },
  { municipality: 'Santa María', department: 'Boyacá', daneCode: '15690' },
  { municipality: 'Santa Rosa de Viterbo', department: 'Boyacá', daneCode: '15693' },
  { municipality: 'Santa Sofía', department: 'Boyacá', daneCode: '15696' },
  { municipality: 'Santana', department: 'Boyacá', daneCode: '15686' },
  { municipality: 'Sativanorte', department: 'Boyacá', daneCode: '15720' },
  { municipality: 'Sativasur', department: 'Boyacá', daneCode: '15723' },
  { municipality: 'Siachoque', department: 'Boyacá', daneCode: '15740' },
  { municipality: 'Soatá', department: 'Boyacá', daneCode: '15753' },
  { municipality: 'Socha', department: 'Boyacá', daneCode: '15757' },
  { municipality: 'Socotá', department: 'Boyacá', daneCode: '15755' },
  { municipality: 'Sogamoso', department: 'Boyacá', daneCode: '15759' },
  { municipality: 'Somondoco', department: 'Boyacá', daneCode: '15761' },
  { municipality: 'Sora', department: 'Boyacá', daneCode: '15762' },
  { municipality: 'Soracá', department: 'Boyacá', daneCode: '15764' },
  { municipality: 'Sotaquirá', department: 'Boyacá', daneCode: '15763' },
  { municipality: 'Susacón', department: 'Boyacá', daneCode: '15774' },
  { municipality: 'Sutamarchán', department: 'Boyacá', daneCode: '15776' },
  { municipality: 'Sutatenza', department: 'Boyacá', daneCode: '15778' },
  { municipality: 'Tasco', department: 'Boyacá', daneCode: '15790' },
  { municipality: 'Tenza', department: 'Boyacá', daneCode: '15798' },
  { municipality: 'Tibaná', department: 'Boyacá', daneCode: '15804' },
  { municipality: 'Tibasosa', department: 'Boyacá', daneCode: '15806' },
  { municipality: 'Tinjacá', department: 'Boyacá', daneCode: '15808' },
  { municipality: 'Tipacoque', department: 'Boyacá', daneCode: '15810' },
  { municipality: 'Toca', department: 'Boyacá', daneCode: '15814' },
  { municipality: 'Togüí', department: 'Boyacá', daneCode: '15816' },
  { municipality: 'Tópaga', department: 'Boyacá', daneCode: '15820' },
  { municipality: 'Tota', department: 'Boyacá', daneCode: '15822' },
  { municipality: 'Tununguá', department: 'Boyacá', daneCode: '15832' },
  { municipality: 'Turmequé', department: 'Boyacá', daneCode: '15835' },
  { municipality: 'Tuta', department: 'Boyacá', daneCode: '15837' },
  { municipality: 'Tutazá', department: 'Boyacá', daneCode: '15839' },
  { municipality: 'Úmbita', department: 'Boyacá', daneCode: '15842' },
  { municipality: 'Ventaquemada', department: 'Boyacá', daneCode: '15861' },
  { municipality: 'Villa de Leyva', department: 'Boyacá', daneCode: '15407' },
  { municipality: 'Viracachá', department: 'Boyacá', daneCode: '15879' },
  { municipality: 'Zetaquira', department: 'Boyacá', daneCode: '15897' },
  { municipality: 'Manizales', department: 'Caldas', daneCode: '17001' },
  { municipality: 'Aguadas', department: 'Caldas', daneCode: '17013' },
  { municipality: 'Anserma', department: 'Caldas', daneCode: '17042' },
  { municipality: 'Aranzazu', department: 'Caldas', daneCode: '17050' },
  { municipality: 'Belalcázar', department: 'Caldas', daneCode: '17088' },
  { municipality: 'Chinchiná', department: 'Caldas', daneCode: '17174' },
  { municipality: 'Filadelfia', department: 'Caldas', daneCode: '17272' },
  { municipality: 'La Dorada', department: 'Caldas', daneCode: '17380' },
  { municipality: 'La Merced', department: 'Caldas', daneCode: '17388' },
  { municipality: 'Manzanares', department: 'Caldas', daneCode: '17433' },
  { municipality: 'Marmato', department: 'Caldas', daneCode: '17442' },
  { municipality: 'Marquetalia', department: 'Caldas', daneCode: '17444' },
  { municipality: 'Marulanda', department: 'Caldas', daneCode: '17446' },
  { municipality: 'Neira', department: 'Caldas', daneCode: '17486' },
  { municipality: 'Norcasia', department: 'Caldas', daneCode: '17495' },
  { municipality: 'Pácora', department: 'Caldas', daneCode: '17513' },
  { municipality: 'Palestina', department: 'Caldas', daneCode: '17524' },
  { municipality: 'Pensilvania', department: 'Caldas', daneCode: '17541' },
  { municipality: 'Riosucio', department: 'Caldas', daneCode: '17614' },
  { municipality: 'Risaralda', department: 'Caldas', daneCode: '17616' },
  { municipality: 'Salamina', department: 'Caldas', daneCode: '17653' },
  { municipality: 'Samaná', department: 'Caldas', daneCode: '17662' },
  { municipality: 'San José', department: 'Caldas', daneCode: '17665' },
  { municipality: 'Supía', department: 'Caldas', daneCode: '17777' },
  { municipality: 'Victoria', department: 'Caldas', daneCode: '17867' },
  { municipality: 'Villamaría', department: 'Caldas', daneCode: '17873' },
  { municipality: 'Viterbo', department: 'Caldas', daneCode: '17877' },
  { municipality: 'Florencia', department: 'Caquetá', daneCode: '18001' },
  { municipality: 'Albania', department: 'Caquetá', daneCode: '18029' },
  { municipality: 'Belén de los Andaquíes', department: 'Caquetá', daneCode: '18094' },
  { municipality: 'Cartagena del Chairá', department: 'Caquetá', daneCode: '18150' },
  { municipality: 'Curillo', department: 'Caquetá', daneCode: '18205' },
  { municipality: 'El Doncello', department: 'Caquetá', daneCode: '18247' },
  { municipality: 'El Paujíl', department: 'Caquetá', daneCode: '18256' },
  { municipality: 'La Montañita', department: 'Caquetá', daneCode: '18410' },
  { municipality: 'Milán', department: 'Caquetá', daneCode: '18460' },
  { municipality: 'Morelia', department: 'Caquetá', daneCode: '18479' },
  { municipality: 'Puerto Rico', department: 'Caquetá', daneCode: '18592' },
  { municipality: 'San José del Fragua', department: 'Caquetá', daneCode: '18610' },
  { municipality: 'San Vicente del Caguán', department: 'Caquetá', daneCode: '18753' },
  { municipality: 'Solano', department: 'Caquetá', daneCode: '18756' },
  { municipality: 'Solita', department: 'Caquetá', daneCode: '18785' },
  { municipality: 'Valparaíso', department: 'Caquetá', daneCode: '18860' },
  { municipality: 'Yopal', department: 'Casanare', daneCode: '85001' },
  { municipality: 'Aguazul', department: 'Casanare', daneCode: '85010' },
  { municipality: 'Chámeza', department: 'Casanare', daneCode: '85015' },
  { municipality: 'Hato Corozal', department: 'Casanare', daneCode: '85125' },
  { municipality: 'La Salina', department: 'Casanare', daneCode: '85136' },
  { municipality: 'Maní', department: 'Casanare', daneCode: '85139' },
  { municipality: 'Monterrey', department: 'Casanare', daneCode: '85162' },
  { municipality: 'Nunchía', department: 'Casanare', daneCode: '85225' },
  { municipality: 'Orocué', department: 'Casanare', daneCode: '85230' },
  { municipality: 'Paz de Ariporo', department: 'Casanare', daneCode: '85250' },
  { municipality: 'Pore', department: 'Casanare', daneCode: '85263' },
  { municipality: 'Recetor', department: 'Casanare', daneCode: '85279' },
  { municipality: 'Sabanalarga', department: 'Casanare', daneCode: '85300' },
  { municipality: 'Sácama', department: 'Casanare', daneCode: '85315' },
  { municipality: 'San Luis de Palenque', department: 'Casanare', daneCode: '85325' },
  { municipality: 'Támara', department: 'Casanare', daneCode: '85400' },
  { municipality: 'Tauramena', department: 'Casanare', daneCode: '85410' },
  { municipality: 'Trinidad', department: 'Casanare', daneCode: '85430' },
  { municipality: 'Villanueva', department: 'Casanare', daneCode: '85440' },
  { municipality: 'Popayán', department: 'Cauca', daneCode: '19001' },
  { municipality: 'Almaguer', department: 'Cauca', daneCode: '19022' },
  { municipality: 'Argelia', department: 'Cauca', daneCode: '19050' },
  { municipality: 'Balboa', department: 'Cauca', daneCode: '19075' },
  { municipality: 'Bolívar', department: 'Cauca', daneCode: '19100' },
  { municipality: 'Buenos Aires', department: 'Cauca', daneCode: '19110' },
  { municipality: 'Cajibío', department: 'Cauca', daneCode: '19130' },
  { municipality: 'Caldono', department: 'Cauca', daneCode: '19137' },
  { municipality: 'Caloto', department: 'Cauca', daneCode: '19142' },
  { municipality: 'Corinto', department: 'Cauca', daneCode: '19212' },
  { municipality: 'El Tambo', department: 'Cauca', daneCode: '19256' },
  { municipality: 'Florencia', department: 'Cauca', daneCode: '19290' },
  { municipality: 'Guachené', department: 'Cauca', daneCode: '19300' },
  { municipality: 'Guapí', department: 'Cauca', daneCode: '19318' },
  { municipality: 'Inzá', department: 'Cauca', daneCode: '19355' },
  { municipality: 'Jambaló', department: 'Cauca', daneCode: '19364' },
  { municipality: 'La Sierra', department: 'Cauca', daneCode: '19392' },
  { municipality: 'La Vega', department: 'Cauca', daneCode: '19397' },
  { municipality: 'López de Micay', department: 'Cauca', daneCode: '19418' },
  { municipality: 'Mercaderes', department: 'Cauca', daneCode: '19450' },
  { municipality: 'Miranda', department: 'Cauca', daneCode: '19455' },
  { municipality: 'Morales', department: 'Cauca', daneCode: '19473' },
  { municipality: 'Padilla', department: 'Cauca', daneCode: '19513' },
  { municipality: 'Páez', department: 'Cauca', daneCode: '19517' },
  { municipality: 'Patía', department: 'Cauca', daneCode: '19532' },
  { municipality: 'Piamonte', department: 'Cauca', daneCode: '19533' },
  { municipality: 'Piendamó', department: 'Cauca', daneCode: '19548' },
  { municipality: 'Puerto Tejada', department: 'Cauca', daneCode: '19573' },
  { municipality: 'Puracé', department: 'Cauca', daneCode: '19585' },
  { municipality: 'Rosas', department: 'Cauca', daneCode: '19622' },
  { municipality: 'San Sebastián', department: 'Cauca', daneCode: '19693' },
  { municipality: 'Santander de Quilichao', department: 'Cauca', daneCode: '19698' },
  { municipality: 'Santa Rosa', department: 'Cauca', daneCode: '19701' },
  { municipality: 'Silvia', department: 'Cauca', daneCode: '19743' },
  { municipality: 'Sotará', department: 'Cauca', daneCode: '19760' },
  { municipality: 'Suárez', department: 'Cauca', daneCode: '19780' },
  { municipality: 'Sucre', department: 'Cauca', daneCode: '19785' },
  { municipality: 'Timbío', department: 'Cauca', daneCode: '19807' },
  { municipality: 'Timbiquí', department: 'Cauca', daneCode: '19809' },
  { municipality: 'Toribío', department: 'Cauca', daneCode: '19821' },
  { municipality: 'Totoró', department: 'Cauca', daneCode: '19824' },
  { municipality: 'Villa Rica', department: 'Cauca', daneCode: '19845' },
  { municipality: 'Valledupar', department: 'Cesar', daneCode: '20001' },
  { municipality: 'Aguachica', department: 'Cesar', daneCode: '20011' },
  { municipality: 'Agustín Codazzi', department: 'Cesar', daneCode: '20013' },
  { municipality: 'Astrea', department: 'Cesar', daneCode: '20032' },
  { municipality: 'Becerril', department: 'Cesar', daneCode: '20045' },
  { municipality: 'Bosconia', department: 'Cesar', daneCode: '20060' },
  { municipality: 'Chimichagua', department: 'Cesar', daneCode: '20175' },
  { municipality: 'Chiriguaná', department: 'Cesar', daneCode: '20178' },
  { municipality: 'Curumaní', department: 'Cesar', daneCode: '20228' },
  { municipality: 'El Copey', department: 'Cesar', daneCode: '20238' },
  { municipality: 'El Paso', department: 'Cesar', daneCode: '20250' },
  { municipality: 'Gamarra', department: 'Cesar', daneCode: '20295' },
  { municipality: 'González', department: 'Cesar', daneCode: '20310' },
  { municipality: 'La Gloria', department: 'Cesar', daneCode: '20383' },
  { municipality: 'La Jagua de Ibirico', department: 'Cesar', daneCode: '20400' },
  { municipality: 'La Paz', department: 'Cesar', daneCode: '20621' },
  { municipality: 'Manaure Balcón del Cesar', department: 'Cesar', daneCode: '20443' },
  { municipality: 'Pailitas', department: 'Cesar', daneCode: '20517' },
  { municipality: 'Pelaya', department: 'Cesar', daneCode: '20550' },
  { municipality: 'Pueblo Bello', department: 'Cesar', daneCode: '20570' },
  { municipality: 'Río de Oro', department: 'Cesar', daneCode: '20614' },
  { municipality: 'San Alberto', department: 'Cesar', daneCode: '20710' },
  { municipality: 'San Diego', department: 'Cesar', daneCode: '20750' },
  { municipality: 'San Martín', department: 'Cesar', daneCode: '20770' },
  { municipality: 'Tamalameque', department: 'Cesar', daneCode: '20787' },
  { municipality: 'Quibdó', department: 'Chocó', daneCode: '27001' },
  { municipality: 'Acandí', department: 'Chocó', daneCode: '27006' },
  { municipality: 'Alto Baudó', department: 'Chocó', daneCode: '27025' },
  { municipality: 'Atrato', department: 'Chocó', daneCode: '27050' },
  { municipality: 'Bagadó', department: 'Chocó', daneCode: '27073' },
  { municipality: 'Bahía Solano', department: 'Chocó', daneCode: '27075' },
  { municipality: 'Bajo Baudó', department: 'Chocó', daneCode: '27077' },
  { municipality: 'Bojayá', department: 'Chocó', daneCode: '27099' },
  { municipality: 'Carmen del Darién', department: 'Chocó', daneCode: '27150' },
  { municipality: 'Cértegui', department: 'Chocó', daneCode: '27160' },
  { municipality: 'Condoto', department: 'Chocó', daneCode: '27205' },
  { municipality: 'El Cantón del San Pablo', department: 'Chocó', daneCode: '27135' },
  { municipality: 'El Carmen de Atrato', department: 'Chocó', daneCode: '27245' },
  { municipality: 'El Litoral del San Juan', department: 'Chocó', daneCode: '27250' },
  { municipality: 'Istmina', department: 'Chocó', daneCode: '27361' },
  { municipality: 'Juradó', department: 'Chocó', daneCode: '27372' },
  { municipality: 'Lloró', department: 'Chocó', daneCode: '27413' },
  { municipality: 'Medio Atrato', department: 'Chocó', daneCode: '27425' },
  { municipality: 'Medio Baudó', department: 'Chocó', daneCode: '27430' },
  { municipality: 'Medio San Juan', department: 'Chocó', daneCode: '27450' },
  { municipality: 'Nóvita', department: 'Chocó', daneCode: '27491' },
  { municipality: 'Nuquí', department: 'Chocó', daneCode: '27495' },
  { municipality: 'Río Iró', department: 'Chocó', daneCode: '27580' },
  { municipality: 'Río Quito', department: 'Chocó', daneCode: '27600' },
  { municipality: 'Riosucio', department: 'Chocó', daneCode: '27615' },
  { municipality: 'San José del Palmar', department: 'Chocó', daneCode: '27660' },
  { municipality: 'Sipí', department: 'Chocó', daneCode: '27745' },
  { municipality: 'Tadó', department: 'Chocó', daneCode: '27787' },
  { municipality: 'Unguía', department: 'Chocó', daneCode: '27800' },
  { municipality: 'Unión Panamericana', department: 'Chocó', daneCode: '27810' },
  { municipality: 'Montería', department: 'Córdoba', daneCode: '23001' },
  { municipality: 'Ayapel', department: 'Córdoba', daneCode: '23068' },
  { municipality: 'Buenavista', department: 'Córdoba', daneCode: '23079' },
  { municipality: 'Canalete', department: 'Córdoba', daneCode: '23090' },
  { municipality: 'Cereté', department: 'Córdoba', daneCode: '23162' },
  { municipality: 'Chimá', department: 'Córdoba', daneCode: '23168' },
  { municipality: 'Chinú', department: 'Córdoba', daneCode: '23182' },
  { municipality: 'Ciénaga de Oro', department: 'Córdoba', daneCode: '23189' },
  { municipality: 'Cotorra', department: 'Córdoba', daneCode: '23300' },
  { municipality: 'La Apartada', department: 'Córdoba', daneCode: '23350' },
  { municipality: 'Lorica', department: 'Córdoba', daneCode: '23417' },
  { municipality: 'Los Córdobas', department: 'Córdoba', daneCode: '23419' },
  { municipality: 'Momil', department: 'Córdoba', daneCode: '23464' },
  { municipality: 'Montelíbano', department: 'Córdoba', daneCode: '23466' },
  { municipality: 'Moñitos', department: 'Córdoba', daneCode: '23500' },
  { municipality: 'Planeta Rica', department: 'Córdoba', daneCode: '23555' },
  { municipality: 'Pueblo Nuevo', department: 'Córdoba', daneCode: '23570' },
  { municipality: 'Puerto Escondido', department: 'Córdoba', daneCode: '23574' },
  { municipality: 'Puerto Libertador', department: 'Córdoba', daneCode: '23580' },
  { municipality: 'Purísima de la Concepción', department: 'Córdoba', daneCode: '23586' },
  { municipality: 'Sahagún', department: 'Córdoba', daneCode: '23660' },
  { municipality: 'San Andrés de Sotavento', department: 'Córdoba', daneCode: '23670' },
  { municipality: 'San Antero', department: 'Córdoba', daneCode: '23672' },
  { municipality: 'San Bernardo del Viento', department: 'Córdoba', daneCode: '23675' },
  { municipality: 'San Carlos', department: 'Córdoba', daneCode: '23678' },
  { municipality: 'San José de Uré', department: 'Córdoba', daneCode: '23682' },
  { municipality: 'San Pelayo', department: 'Córdoba', daneCode: '23686' },
  { municipality: 'Tierralta', department: 'Córdoba', daneCode: '23807' },
  { municipality: 'Tuchín', department: 'Córdoba', daneCode: '23815' },
  { municipality: 'Valencia', department: 'Córdoba', daneCode: '23855' },
  { municipality: 'Agua de Dios', department: 'Cundinamarca', daneCode: '25001' },
  { municipality: 'Albán', department: 'Cundinamarca', daneCode: '25019' },
  { municipality: 'Anapoima', department: 'Cundinamarca', daneCode: '25035' },
  { municipality: 'Anolaima', department: 'Cundinamarca', daneCode: '25040' },
  { municipality: 'Arbeláez', department: 'Cundinamarca', daneCode: '25053' },
  { municipality: 'Beltrán', department: 'Cundinamarca', daneCode: '25086' },
  { municipality: 'Bituima', department: 'Cundinamarca', daneCode: '25095' },
  { municipality: 'Bojacá', department: 'Cundinamarca', daneCode: '25099' },
  { municipality: 'Cabrera', department: 'Cundinamarca', daneCode: '25120' },
  { municipality: 'Cachipay', department: 'Cundinamarca', daneCode: '25123' },
  { municipality: 'Cajicá', department: 'Cundinamarca', daneCode: '25126' },
  { municipality: 'Caparrapí', department: 'Cundinamarca', daneCode: '25148' },
  { municipality: 'Cáqueza', department: 'Cundinamarca', daneCode: '25151' },
  { municipality: 'Carmen de Carupa', department: 'Cundinamarca', daneCode: '25154' },
  { municipality: 'Chaguaní', department: 'Cundinamarca', daneCode: '25168' },
  { municipality: 'Chía', department: 'Cundinamarca', daneCode: '25175' },
  { municipality: 'Chipaque', department: 'Cundinamarca', daneCode: '25178' },
  { municipality: 'Choachí', department: 'Cundinamarca', daneCode: '25181' },
  { municipality: 'Chocontá', department: 'Cundinamarca', daneCode: '25183' },
  { municipality: 'Cogua', department: 'Cundinamarca', daneCode: '25200' },
  { municipality: 'Cota', department: 'Cundinamarca', daneCode: '25214' },
  { municipality: 'Cucunubá', department: 'Cundinamarca', daneCode: '25224' },
  { municipality: 'El Colegio', department: 'Cundinamarca', daneCode: '25245' },
  { municipality: 'El Peñón', department: 'Cundinamarca', daneCode: '25258' },
  { municipality: 'El Rosal', department: 'Cundinamarca', daneCode: '25260' },
  { municipality: 'Facatativá', department: 'Cundinamarca', daneCode: '25269' },
  { municipality: 'Fómeque', department: 'Cundinamarca', daneCode: '25279' },
  { municipality: 'Fosca', department: 'Cundinamarca', daneCode: '25281' },
  { municipality: 'Funza', department: 'Cundinamarca', daneCode: '25286' },
  { municipality: 'Fúquene', department: 'Cundinamarca', daneCode: '25288' },
  { municipality: 'Fusagasugá', department: 'Cundinamarca', daneCode: '25290' },
  { municipality: 'Gachalá', department: 'Cundinamarca', daneCode: '25293' },
  { municipality: 'Gachancipá', department: 'Cundinamarca', daneCode: '25295' },
  { municipality: 'Gachetá', department: 'Cundinamarca', daneCode: '25297' },
  { municipality: 'Gama', department: 'Cundinamarca', daneCode: '25299' },
  { municipality: 'Girardot', department: 'Cundinamarca', daneCode: '25307' },
  { municipality: 'Granada', department: 'Cundinamarca', daneCode: '25312' },
  { municipality: 'Guachetá', department: 'Cundinamarca', daneCode: '25317' },
  { municipality: 'Guaduas', department: 'Cundinamarca', daneCode: '25320' },
  { municipality: 'Guasca', department: 'Cundinamarca', daneCode: '25322' },
  { municipality: 'Guataquí', department: 'Cundinamarca', daneCode: '25324' },
  { municipality: 'Guatavita', department: 'Cundinamarca', daneCode: '25326' },
  { municipality: 'Guayabal de Síquima', department: 'Cundinamarca', daneCode: '25328' },
  { municipality: 'Guayabetal', department: 'Cundinamarca', daneCode: '25335' },
  { municipality: 'Gutiérrez', department: 'Cundinamarca', daneCode: '25339' },
  { municipality: 'Jerusalén', department: 'Cundinamarca', daneCode: '25368' },
  { municipality: 'Junín', department: 'Cundinamarca', daneCode: '25372' },
  { municipality: 'La Calera', department: 'Cundinamarca', daneCode: '25377' },
  { municipality: 'La Mesa', department: 'Cundinamarca', daneCode: '25386' },
  { municipality: 'La Palma', department: 'Cundinamarca', daneCode: '25394' },
  { municipality: 'La Peña', department: 'Cundinamarca', daneCode: '25398' },
  { municipality: 'La Vega', department: 'Cundinamarca', daneCode: '25402' },
  { municipality: 'Lenguazaque', department: 'Cundinamarca', daneCode: '25407' },
  { municipality: 'Machetá', department: 'Cundinamarca', daneCode: '25426' },
  { municipality: 'Madrid', department: 'Cundinamarca', daneCode: '25430' },
  { municipality: 'Manta', department: 'Cundinamarca', daneCode: '25436' },
  { municipality: 'Medina', department: 'Cundinamarca', daneCode: '25438' },
  { municipality: 'Mosquera', department: 'Cundinamarca', daneCode: '25473' },
  { municipality: 'Nariño', department: 'Cundinamarca', daneCode: '25483' },
  { municipality: 'Nemocón', department: 'Cundinamarca', daneCode: '25486' },
  { municipality: 'Nilo', department: 'Cundinamarca', daneCode: '25488' },
  { municipality: 'Nimaima', department: 'Cundinamarca', daneCode: '25489' },
  { municipality: 'Nocaima', department: 'Cundinamarca', daneCode: '25491' },
  { municipality: 'Pacho', department: 'Cundinamarca', daneCode: '25513' },
  { municipality: 'Paime', department: 'Cundinamarca', daneCode: '25518' },
  { municipality: 'Pandi', department: 'Cundinamarca', daneCode: '25524' },
  { municipality: 'Paratebueno', department: 'Cundinamarca', daneCode: '25530' },
  { municipality: 'Pasca', department: 'Cundinamarca', daneCode: '25535' },
  { municipality: 'Puerto Salgar', department: 'Cundinamarca', daneCode: '25572' },
  { municipality: 'Pulí', department: 'Cundinamarca', daneCode: '25580' },
  { municipality: 'Quebradanegra', department: 'Cundinamarca', daneCode: '25592' },
  { municipality: 'Quetame', department: 'Cundinamarca', daneCode: '25594' },
  { municipality: 'Quipile', department: 'Cundinamarca', daneCode: '25596' },
  { municipality: 'Ricaurte', department: 'Cundinamarca', daneCode: '25612' },
  { municipality: 'San Antonio del Tequendama', department: 'Cundinamarca', daneCode: '25645' },
  { municipality: 'San Bernardo', department: 'Cundinamarca', daneCode: '25649' },
  { municipality: 'San Cayetano', department: 'Cundinamarca', daneCode: '25653' },
  { municipality: 'San Francisco', department: 'Cundinamarca', daneCode: '25658' },
  { municipality: 'San Juan de Rioseco', department: 'Cundinamarca', daneCode: '25662' },
  { municipality: 'Sasaima', department: 'Cundinamarca', daneCode: '25718' },
  { municipality: 'Sesquilé', department: 'Cundinamarca', daneCode: '25736' },
  { municipality: 'Sibaté', department: 'Cundinamarca', daneCode: '25740' },
  { municipality: 'Silvania', department: 'Cundinamarca', daneCode: '25743' },
  { municipality: 'Simijaca', department: 'Cundinamarca', daneCode: '25745' },
  { municipality: 'Soacha', department: 'Cundinamarca', daneCode: '25754' },
  { municipality: 'Sopó', department: 'Cundinamarca', daneCode: '25758' },
  { municipality: 'Subachoque', department: 'Cundinamarca', daneCode: '25769' },
  { municipality: 'Suesca', department: 'Cundinamarca', daneCode: '25772' },
  { municipality: 'Supatá', department: 'Cundinamarca', daneCode: '25777' },
  { municipality: 'Susa', department: 'Cundinamarca', daneCode: '25779' },
  { municipality: 'Sutatausa', department: 'Cundinamarca', daneCode: '25781' },
  { municipality: 'Tabio', department: 'Cundinamarca', daneCode: '25785' },
  { municipality: 'Tausa', department: 'Cundinamarca', daneCode: '25793' },
  { municipality: 'Tena', department: 'Cundinamarca', daneCode: '25797' },
  { municipality: 'Tenjo', department: 'Cundinamarca', daneCode: '25799' },
  { municipality: 'Tibacuy', department: 'Cundinamarca', daneCode: '25805' },
  { municipality: 'Tibirita', department: 'Cundinamarca', daneCode: '25807' },
  { municipality: 'Tocaima', department: 'Cundinamarca', daneCode: '25815' },
  { municipality: 'Tocancipá', department: 'Cundinamarca', daneCode: '25817' },
  { municipality: 'Topaipí', department: 'Cundinamarca', daneCode: '25823' },
  { municipality: 'Ubalá', department: 'Cundinamarca', daneCode: '25839' },
  { municipality: 'Ubaque', department: 'Cundinamarca', daneCode: '25841' },
  { municipality: 'Úne', department: 'Cundinamarca', daneCode: '25845' },
  { municipality: 'Útica', department: 'Cundinamarca', daneCode: '25851' },
  { municipality: 'Vergara', department: 'Cundinamarca', daneCode: '25862' },
  { municipality: 'Vianí', department: 'Cundinamarca', daneCode: '25867' },
  { municipality: 'Villa de San Diego de Ubaté', department: 'Cundinamarca', daneCode: '25843' },
  { municipality: 'Villagómez', department: 'Cundinamarca', daneCode: '25871' },
  { municipality: 'Villapinzón', department: 'Cundinamarca', daneCode: '25873' },
  { municipality: 'Villeta', department: 'Cundinamarca', daneCode: '25875' },
  { municipality: 'Viotá', department: 'Cundinamarca', daneCode: '25878' },
  { municipality: 'Yacopí', department: 'Cundinamarca', daneCode: '25885' },
  { municipality: 'Zipacón', department: 'Cundinamarca', daneCode: '25898' },
  { municipality: 'Zipaquirá', department: 'Cundinamarca', daneCode: '25899' },
  { municipality: 'Inírida', department: 'Guainía', daneCode: '94001' },
  { municipality: 'Barrancominas', department: 'Guainía', daneCode: '94343' },
  { municipality: 'San José del Guaviare', department: 'Guaviare', daneCode: '95001' },
  { municipality: 'Calamar', department: 'Guaviare', daneCode: '95015' },
  { municipality: 'El Retorno', department: 'Guaviare', daneCode: '95025' },
  { municipality: 'Miraflores', department: 'Guaviare', daneCode: '95200' },
  { municipality: 'Neiva', department: 'Huila', daneCode: '41001' },
  { municipality: 'Acevedo', department: 'Huila', daneCode: '41006' },
  { municipality: 'Agrado', department: 'Huila', daneCode: '41013' },
  { municipality: 'Aipe', department: 'Huila', daneCode: '41016' },
  { municipality: 'Algeciras', department: 'Huila', daneCode: '41020' },
  { municipality: 'Altamira', department: 'Huila', daneCode: '41026' },
  { municipality: 'Baraya', department: 'Huila', daneCode: '41078' },
  { municipality: 'Campoalegre', department: 'Huila', daneCode: '41132' },
  { municipality: 'Colombia', department: 'Huila', daneCode: '41206' },
  { municipality: 'Elías', department: 'Huila', daneCode: '41244' },
  { municipality: 'Garzón', department: 'Huila', daneCode: '41298' },
  { municipality: 'Gigante', department: 'Huila', daneCode: '41306' },
  { municipality: 'Guadalupe', department: 'Huila', daneCode: '41319' },
  { municipality: 'Hobo', department: 'Huila', daneCode: '41349' },
  { municipality: 'Íquira', department: 'Huila', daneCode: '41357' },
  { municipality: 'Isnos', department: 'Huila', daneCode: '41359' },
  { municipality: 'La Argentina', department: 'Huila', daneCode: '41378' },
  { municipality: 'La Plata', department: 'Huila', daneCode: '41396' },
  { municipality: 'Nátaga', department: 'Huila', daneCode: '41483' },
  { municipality: 'Oporapa', department: 'Huila', daneCode: '41503' },
  { municipality: 'Paicol', department: 'Huila', daneCode: '41518' },
  { municipality: 'Palermo', department: 'Huila', daneCode: '41524' },
  { municipality: 'Palestina', department: 'Huila', daneCode: '41530' },
  { municipality: 'Pital', department: 'Huila', daneCode: '41548' },
  { municipality: 'Pitalito', department: 'Huila', daneCode: '41551' },
  { municipality: 'Rivera', department: 'Huila', daneCode: '41615' },
  { municipality: 'Saladoblanco', department: 'Huila', daneCode: '41660' },
  { municipality: 'San Agustín', department: 'Huila', daneCode: '41668' },
  { municipality: 'Santa María', department: 'Huila', daneCode: '41676' },
  { municipality: 'Suaza', department: 'Huila', daneCode: '41770' },
  { municipality: 'Tarqui', department: 'Huila', daneCode: '41791' },
  { municipality: 'Tesalia', department: 'Huila', daneCode: '41797' },
  { municipality: 'Tello', department: 'Huila', daneCode: '41799' },
  { municipality: 'Teruel', department: 'Huila', daneCode: '41801' },
  { municipality: 'Timaná', department: 'Huila', daneCode: '41807' },
  { municipality: 'Villavieja', department: 'Huila', daneCode: '41872' },
  { municipality: 'Yaguará', department: 'Huila', daneCode: '41885' },
  { municipality: 'Riohacha', department: 'La Guajira', daneCode: '44001' },
  { municipality: 'Albania', department: 'La Guajira', daneCode: '44035' },
  { municipality: 'Barrancas', department: 'La Guajira', daneCode: '44078' },
  { municipality: 'Dibulla', department: 'La Guajira', daneCode: '44090' },
  { municipality: 'Distracción', department: 'La Guajira', daneCode: '44098' },
  { municipality: 'El Molino', department: 'La Guajira', daneCode: '44110' },
  { municipality: 'Fonseca', department: 'La Guajira', daneCode: '44279' },
  { municipality: 'Hatonuevo', department: 'La Guajira', daneCode: '44378' },
  { municipality: 'La Jagua del Pilar', department: 'La Guajira', daneCode: '44420' },
  { municipality: 'Maicao', department: 'La Guajira', daneCode: '44430' },
  { municipality: 'Manaure', department: 'La Guajira', daneCode: '44560' },
  { municipality: 'San Juan del Cesar', department: 'La Guajira', daneCode: '44650' },
  { municipality: 'Uribia', department: 'La Guajira', daneCode: '44847' },
  { municipality: 'Urumita', department: 'La Guajira', daneCode: '44855' },
  { municipality: 'Villanueva', department: 'La Guajira', daneCode: '44874' },
  { municipality: 'Santa Marta', department: 'Magdalena', daneCode: '47001' },
  { municipality: 'Algarrobo', department: 'Magdalena', daneCode: '47030' },
  { municipality: 'Aracataca', department: 'Magdalena', daneCode: '47053' },
  { municipality: 'Ariguaní', department: 'Magdalena', daneCode: '47058' },
  { municipality: 'Cerro de San Antonio', department: 'Magdalena', daneCode: '47161' },
  { municipality: 'Chivolo', department: 'Magdalena', daneCode: '47170' },
  { municipality: 'Ciénaga', department: 'Magdalena', daneCode: '47189' },
  { municipality: 'Concordia', department: 'Magdalena', daneCode: '47205' },
  { municipality: 'El Banco', department: 'Magdalena', daneCode: '47245' },
  { municipality: 'El Piñón', department: 'Magdalena', daneCode: '47258' },
  { municipality: 'El Retén', department: 'Magdalena', daneCode: '47268' },
  { municipality: 'Fundación', department: 'Magdalena', daneCode: '47288' },
  { municipality: 'Guamal', department: 'Magdalena', daneCode: '47318' },
  { municipality: 'Nueva Granada', department: 'Magdalena', daneCode: '47460' },
  { municipality: 'Pedraza', department: 'Magdalena', daneCode: '47541' },
  { municipality: 'Pijiño del Carmen', department: 'Magdalena', daneCode: '47545' },
  { municipality: 'Pivijay', department: 'Magdalena', daneCode: '47551' },
  { municipality: 'Plato', department: 'Magdalena', daneCode: '47555' },
  { municipality: 'Puebloviejo', department: 'Magdalena', daneCode: '47570' },
  { municipality: 'Remolino', department: 'Magdalena', daneCode: '47605' },
  { municipality: 'Sabanas de San Ángel', department: 'Magdalena', daneCode: '47660' },
  { municipality: 'Salamina', department: 'Magdalena', daneCode: '47675' },
  { municipality: 'San Sebastián de Buenavista', department: 'Magdalena', daneCode: '47692' },
  { municipality: 'San Zenón', department: 'Magdalena', daneCode: '47703' },
  { municipality: 'Santa Ana', department: 'Magdalena', daneCode: '47707' },
  { municipality: 'Santa Bárbara de Pinto', department: 'Magdalena', daneCode: '47720' },
  { municipality: 'Sitionuevo', department: 'Magdalena', daneCode: '47745' },
  { municipality: 'Tenerife', department: 'Magdalena', daneCode: '47798' },
  { municipality: 'Zapayán', department: 'Magdalena', daneCode: '47960' },
  { municipality: 'Zona Bananera', department: 'Magdalena', daneCode: '47980' },
  { municipality: 'Villavicencio', department: 'Meta', daneCode: '50001' },
  { municipality: 'Acacías', department: 'Meta', daneCode: '50006' },
  { municipality: 'Barranca de Upía', department: 'Meta', daneCode: '50110' },
  { municipality: 'Cabuyaro', department: 'Meta', daneCode: '50124' },
  { municipality: 'Castilla la Nueva', department: 'Meta', daneCode: '50150' },
  { municipality: 'Cubarral', department: 'Meta', daneCode: '50223' },
  { municipality: 'Cumaral', department: 'Meta', daneCode: '50226' },
  { municipality: 'El Calvario', department: 'Meta', daneCode: '50245' },
  { municipality: 'El Castillo', department: 'Meta', daneCode: '50251' },
  { municipality: 'El Dorado', department: 'Meta', daneCode: '50270' },
  { municipality: 'Fuente de Oro', department: 'Meta', daneCode: '50287' },
  { municipality: 'Granada', department: 'Meta', daneCode: '50313' },
  { municipality: 'Guamal', department: 'Meta', daneCode: '50318' },
  { municipality: 'La Macarena', department: 'Meta', daneCode: '50350' },
  { municipality: 'La Uribe', department: 'Meta', daneCode: '50370' },
  { municipality: 'Lejanías', department: 'Meta', daneCode: '50400' },
  { municipality: 'Mapiripán', department: 'Meta', daneCode: '50325' },
  { municipality: 'Mesetas', department: 'Meta', daneCode: '50330' },
  { municipality: 'Puerto Concordia', department: 'Meta', daneCode: '50450' },
  { municipality: 'Puerto Gaitán', department: 'Meta', daneCode: '50568' },
  { municipality: 'Puerto López', department: 'Meta', daneCode: '50573' },
  { municipality: 'Puerto Lleras', department: 'Meta', daneCode: '50577' },
  { municipality: 'Puerto Rico', department: 'Meta', daneCode: '50590' },
  { municipality: 'Restrepo', department: 'Meta', daneCode: '50606' },
  { municipality: 'San Carlos de Guaroa', department: 'Meta', daneCode: '50680' },
  { municipality: 'San Juan de Arama', department: 'Meta', daneCode: '50683' },
  { municipality: 'San Juanito', department: 'Meta', daneCode: '50686' },
  { municipality: 'San Martín', department: 'Meta', daneCode: '50689' },
  { municipality: 'Vistahermosa', department: 'Meta', daneCode: '50711' },
  { municipality: 'Pasto', department: 'Nariño', daneCode: '52001' },
  { municipality: 'Albán', department: 'Nariño', daneCode: '52019' },
  { municipality: 'Aldana', department: 'Nariño', daneCode: '52022' },
  { municipality: 'Ancuyá', department: 'Nariño', daneCode: '52036' },
  { municipality: 'Arboleda', department: 'Nariño', daneCode: '52051' },
  { municipality: 'Barbacoas', department: 'Nariño', daneCode: '52079' },
  { municipality: 'Belén', department: 'Nariño', daneCode: '52083' },
  { municipality: 'Buesaco', department: 'Nariño', daneCode: '52110' },
  { municipality: 'Chachagüí', department: 'Nariño', daneCode: '52240' },
  { municipality: 'Colón', department: 'Nariño', daneCode: '52203' },
  { municipality: 'Consacá', department: 'Nariño', daneCode: '52207' },
  { municipality: 'Contadero', department: 'Nariño', daneCode: '52210' },
  { municipality: 'Córdoba', department: 'Nariño', daneCode: '52215' },
  { municipality: 'Cuaspúd', department: 'Nariño', daneCode: '52224' },
  { municipality: 'Cumbal', department: 'Nariño', daneCode: '52227' },
  { municipality: 'Cumbitara', department: 'Nariño', daneCode: '52233' },
  { municipality: 'El Charco', department: 'Nariño', daneCode: '52250' },
  { municipality: 'El Peñol', department: 'Nariño', daneCode: '52254' },
  { municipality: 'El Rosario', department: 'Nariño', daneCode: '52256' },
  { municipality: 'El Tablón de Gómez', department: 'Nariño', daneCode: '52258' },
  { municipality: 'El Tambo', department: 'Nariño', daneCode: '52260' },
  { municipality: 'Francisco Pizarro', department: 'Nariño', daneCode: '52520' },
  { municipality: 'Funes', department: 'Nariño', daneCode: '52287' },
  { municipality: 'Guachucal', department: 'Nariño', daneCode: '52317' },
  { municipality: 'Guaitarilla', department: 'Nariño', daneCode: '52320' },
  { municipality: 'Gualmatán', department: 'Nariño', daneCode: '52323' },
  { municipality: 'Iles', department: 'Nariño', daneCode: '52352' },
  { municipality: 'Imués', department: 'Nariño', daneCode: '52354' },
  { municipality: 'Ipiales', department: 'Nariño', daneCode: '52356' },
  { municipality: 'La Cruz', department: 'Nariño', daneCode: '52378' },
  { municipality: 'La Florida', department: 'Nariño', daneCode: '52381' },
  { municipality: 'La Llanada', department: 'Nariño', daneCode: '52385' },
  { municipality: 'La Tola', department: 'Nariño', daneCode: '52390' },
  { municipality: 'La Unión', department: 'Nariño', daneCode: '52399' },
  { municipality: 'Leiva', department: 'Nariño', daneCode: '52405' },
  { municipality: 'Linares', department: 'Nariño', daneCode: '52411' },
  { municipality: 'Los Andes', department: 'Nariño', daneCode: '52418' },
  { municipality: 'Magüí Payán', department: 'Nariño', daneCode: '52427' },
  { municipality: 'Mallama', department: 'Nariño', daneCode: '52435' },
  { municipality: 'Mosquera', department: 'Nariño', daneCode: '52473' },
  { municipality: 'Nariño', department: 'Nariño', daneCode: '52480' },
  { municipality: 'Olaya Herrera', department: 'Nariño', daneCode: '52490' },
  { municipality: 'Ospina', department: 'Nariño', daneCode: '52506' },
  { municipality: 'Policarpa', department: 'Nariño', daneCode: '52540' },
  { municipality: 'Potosí', department: 'Nariño', daneCode: '52560' },
  { municipality: 'Providencia', department: 'Nariño', daneCode: '52565' },
  { municipality: 'Puerres', department: 'Nariño', daneCode: '52573' },
  { municipality: 'Pupiales', department: 'Nariño', daneCode: '52585' },
  { municipality: 'Ricaurte', department: 'Nariño', daneCode: '52612' },
  { municipality: 'Roberto Payán', department: 'Nariño', daneCode: '52621' },
  { municipality: 'Samaniego', department: 'Nariño', daneCode: '52678' },
  { municipality: 'San Bernardo', department: 'Nariño', daneCode: '52685' },
  { municipality: 'San Lorenzo', department: 'Nariño', daneCode: '52687' },
  { municipality: 'San Pablo', department: 'Nariño', daneCode: '52693' },
  { municipality: 'San Pedro de Cartago', department: 'Nariño', daneCode: '52694' },
  { municipality: 'Sandoná', department: 'Nariño', daneCode: '52683' },
  { municipality: 'Santa Bárbara', department: 'Nariño', daneCode: '52696' },
  { municipality: 'Santacruz', department: 'Nariño', daneCode: '52699' },
  { municipality: 'Sapuyes', department: 'Nariño', daneCode: '52720' },
  { municipality: 'Taminango', department: 'Nariño', daneCode: '52786' },
  { municipality: 'Tangua', department: 'Nariño', daneCode: '52788' },
  { municipality: 'Tumaco', department: 'Nariño', daneCode: '52835' },
  { municipality: 'Túquerres', department: 'Nariño', daneCode: '52838' },
  { municipality: 'Yacuanquer', department: 'Nariño', daneCode: '52885' },
  { municipality: 'Cúcuta', department: 'Norte de Santander', daneCode: '54001' },
  { municipality: 'Ábrego', department: 'Norte de Santander', daneCode: '54003' },
  { municipality: 'Arboledas', department: 'Norte de Santander', daneCode: '54051' },
  { municipality: 'Bochalema', department: 'Norte de Santander', daneCode: '54099' },
  { municipality: 'Bucarasica', department: 'Norte de Santander', daneCode: '54109' },
  { municipality: 'Cáchira', department: 'Norte de Santander', daneCode: '54128' },
  { municipality: 'Cácota', department: 'Norte de Santander', daneCode: '54125' },
  { municipality: 'Chinácota', department: 'Norte de Santander', daneCode: '54172' },
  { municipality: 'Chitagá', department: 'Norte de Santander', daneCode: '54174' },
  { municipality: 'Convención', department: 'Norte de Santander', daneCode: '54206' },
  { municipality: 'Cucutilla', department: 'Norte de Santander', daneCode: '54223' },
  { municipality: 'Durania', department: 'Norte de Santander', daneCode: '54239' },
  { municipality: 'El Carmen', department: 'Norte de Santander', daneCode: '54245' },
  { municipality: 'El Tarra', department: 'Norte de Santander', daneCode: '54250' },
  { municipality: 'El Zulia', department: 'Norte de Santander', daneCode: '54261' },
  { municipality: 'Gramalote', department: 'Norte de Santander', daneCode: '54313' },
  { municipality: 'Hacarí', department: 'Norte de Santander', daneCode: '54344' },
  { municipality: 'Herrán', department: 'Norte de Santander', daneCode: '54347' },
  { municipality: 'La Esperanza', department: 'Norte de Santander', daneCode: '54385' },
  { municipality: 'La Playa de Belén', department: 'Norte de Santander', daneCode: '54398' },
  { municipality: 'Labateca', department: 'Norte de Santander', daneCode: '54377' },
  { municipality: 'Los Patios', department: 'Norte de Santander', daneCode: '54405' },
  { municipality: 'Lourdes', department: 'Norte de Santander', daneCode: '54418' },
  { municipality: 'Mutiscua', department: 'Norte de Santander', daneCode: '54480' },
  { municipality: 'Ocaña', department: 'Norte de Santander', daneCode: '54498' },
  { municipality: 'Pamplona', department: 'Norte de Santander', daneCode: '54518' },
  { municipality: 'Pamplonita', department: 'Norte de Santander', daneCode: '54520' },
  { municipality: 'Puerto Santander', department: 'Norte de Santander', daneCode: '54553' },
  { municipality: 'Ragonvalia', department: 'Norte de Santander', daneCode: '54599' },
  { municipality: 'Salazar de las Palmas', department: 'Norte de Santander', daneCode: '54660' },
  { municipality: 'San Calixto', department: 'Norte de Santander', daneCode: '54670' },
  { municipality: 'San Cayetano', department: 'Norte de Santander', daneCode: '54673' },
  { municipality: 'Santiago', department: 'Norte de Santander', daneCode: '54680' },
  { municipality: 'Sardinata', department: 'Norte de Santander', daneCode: '54720' },
  { municipality: 'Silos', department: 'Norte de Santander', daneCode: '54743' },
  { municipality: 'Teorama', department: 'Norte de Santander', daneCode: '54800' },
  { municipality: 'Tibú', department: 'Norte de Santander', daneCode: '54810' },
  { municipality: 'Toledo', department: 'Norte de Santander', daneCode: '54820' },
  { municipality: 'Villa Caro', department: 'Norte de Santander', daneCode: '54871' },
  { municipality: 'Villa del Rosario', department: 'Norte de Santander', daneCode: '54874' },
  { municipality: 'Mocoa', department: 'Putumayo', daneCode: '86001' },
  { municipality: 'Colón', department: 'Putumayo', daneCode: '86219' },
  { municipality: 'Orito', department: 'Putumayo', daneCode: '86320' },
  { municipality: 'Puerto Asís', department: 'Putumayo', daneCode: '86568' },
  { municipality: 'Puerto Caicedo', department: 'Putumayo', daneCode: '86569' },
  { municipality: 'Puerto Guzmán', department: 'Putumayo', daneCode: '86571' },
  { municipality: 'Puerto Leguízamo', department: 'Putumayo', daneCode: '86573' },
  { municipality: 'San Francisco', department: 'Putumayo', daneCode: '86755' },
  { municipality: 'San Miguel', department: 'Putumayo', daneCode: '86757' },
  { municipality: 'Santiago', department: 'Putumayo', daneCode: '86760' },
  { municipality: 'Sibundoy', department: 'Putumayo', daneCode: '86749' },
  { municipality: 'Valle del Guamuez', department: 'Putumayo', daneCode: '86865' },
  { municipality: 'Villagarzón', department: 'Putumayo', daneCode: '86885' },
  { municipality: 'Armenia', department: 'Quindío', daneCode: '63001' },
  { municipality: 'Buenavista', department: 'Quindío', daneCode: '63111' },
  { municipality: 'Calarcá', department: 'Quindío', daneCode: '63130' },
  { municipality: 'Circasia', department: 'Quindío', daneCode: '63190' },
  { municipality: 'Córdoba', department: 'Quindío', daneCode: '63212' },
  { municipality: 'Filandia', department: 'Quindío', daneCode: '63272' },
  { municipality: 'Génova', department: 'Quindío', daneCode: '63302' },
  { municipality: 'La Tebaida', department: 'Quindío', daneCode: '63401' },
  { municipality: 'Montenegro', department: 'Quindío', daneCode: '63470' },
  { municipality: 'Pijao', department: 'Quindío', daneCode: '63548' },
  { municipality: 'Quimbaya', department: 'Quindío', daneCode: '63594' },
  { municipality: 'Salento', department: 'Quindío', daneCode: '63690' },
  { municipality: 'Pereira', department: 'Risaralda', daneCode: '66001' },
  { municipality: 'Apía', department: 'Risaralda', daneCode: '66045' },
  { municipality: 'Balboa', department: 'Risaralda', daneCode: '66075' },
  { municipality: 'Belén de Umbría', department: 'Risaralda', daneCode: '66088' },
  { municipality: 'Dosquebradas', department: 'Risaralda', daneCode: '66170' },
  { municipality: 'Guática', department: 'Risaralda', daneCode: '66318' },
  { municipality: 'La Celia', department: 'Risaralda', daneCode: '66383' },
  { municipality: 'La Virginia', department: 'Risaralda', daneCode: '66400' },
  { municipality: 'Marsella', department: 'Risaralda', daneCode: '66440' },
  { municipality: 'Mistrató', department: 'Risaralda', daneCode: '66456' },
  { municipality: 'Pueblo Rico', department: 'Risaralda', daneCode: '66572' },
  { municipality: 'Quinchía', department: 'Risaralda', daneCode: '66594' },
  { municipality: 'Santa Rosa de Cabal', department: 'Risaralda', daneCode: '66682' },
  { municipality: 'Santuario', department: 'Risaralda', daneCode: '66687' },
  { municipality: 'San Andrés', department: 'San Andrés y Providencia', daneCode: '88001' },
  { municipality: 'Providencia', department: 'San Andrés y Providencia', daneCode: '88564' },
  { municipality: 'Bucaramanga', department: 'Santander', daneCode: '68001' },
  { municipality: 'Aguada', department: 'Santander', daneCode: '68013' },
  { municipality: 'Albania', department: 'Santander', daneCode: '68020' },
  { municipality: 'Aratoca', department: 'Santander', daneCode: '68051' },
  { municipality: 'Barbosa', department: 'Santander', daneCode: '68077' },
  { municipality: 'Barichara', department: 'Santander', daneCode: '68079' },
  { municipality: 'Barrancabermeja', department: 'Santander', daneCode: '68081' },
  { municipality: 'Betulia', department: 'Santander', daneCode: '68092' },
  { municipality: 'Bolívar', department: 'Santander', daneCode: '68101' },
  { municipality: 'Cabrera', department: 'Santander', daneCode: '68121' },
  { municipality: 'California', department: 'Santander', daneCode: '68132' },
  { municipality: 'Capitanejo', department: 'Santander', daneCode: '68147' },
  { municipality: 'Carcasí', department: 'Santander', daneCode: '68152' },
  { municipality: 'Cepitá', department: 'Santander', daneCode: '68160' },
  { municipality: 'Cerrito', department: 'Santander', daneCode: '68162' },
  { municipality: 'Charalá', department: 'Santander', daneCode: '68167' },
  { municipality: 'Charta', department: 'Santander', daneCode: '68169' },
  { municipality: 'Chimá', department: 'Santander', daneCode: '68176' },
  { municipality: 'Chipatá', department: 'Santander', daneCode: '68179' },
  { municipality: 'Cimitarra', department: 'Santander', daneCode: '68190' },
  { municipality: 'Concepción', department: 'Santander', daneCode: '68207' },
  { municipality: 'Confines', department: 'Santander', daneCode: '68209' },
  { municipality: 'Contratación', department: 'Santander', daneCode: '68211' },
  { municipality: 'Coromoro', department: 'Santander', daneCode: '68217' },
  { municipality: 'Curití', department: 'Santander', daneCode: '68229' },
  { municipality: 'El Carmen de Chucurí', department: 'Santander', daneCode: '68235' },
  { municipality: 'El Guacamayo', department: 'Santander', daneCode: '68245' },
  { municipality: 'El Peñón', department: 'Santander', daneCode: '68250' },
  { municipality: 'El Playón', department: 'Santander', daneCode: '68255' },
  { municipality: 'Encino', department: 'Santander', daneCode: '68264' },
  { municipality: 'Enciso', department: 'Santander', daneCode: '68266' },
  { municipality: 'Florián', department: 'Santander', daneCode: '68271' },
  { municipality: 'Floridablanca', department: 'Santander', daneCode: '68276' },
  { municipality: 'Galán', department: 'Santander', daneCode: '68296' },
  { municipality: 'Gámbita', department: 'Santander', daneCode: '68298' },
  { municipality: 'Girón', department: 'Santander', daneCode: '68307' },
  { municipality: 'Guaca', department: 'Santander', daneCode: '68318' },
  { municipality: 'Guadalupe', department: 'Santander', daneCode: '68320' },
  { municipality: 'Guapotá', department: 'Santander', daneCode: '68322' },
  { municipality: 'Guavatá', department: 'Santander', daneCode: '68324' },
  { municipality: 'Güepsa', department: 'Santander', daneCode: '68327' },
  { municipality: 'Hato', department: 'Santander', daneCode: '68344' },
  { municipality: 'Jesús María', department: 'Santander', daneCode: '68368' },
  { municipality: 'Jordán', department: 'Santander', daneCode: '68370' },
  { municipality: 'La Belleza', department: 'Santander', daneCode: '68377' },
  { municipality: 'La Paz', department: 'Santander', daneCode: '68397' },
  { municipality: 'Landázuri', department: 'Santander', daneCode: '68385' },
  { municipality: 'Lebríja', department: 'Santander', daneCode: '68406' },
  { municipality: 'Los Santos', department: 'Santander', daneCode: '68418' },
  { municipality: 'Macaravita', department: 'Santander', daneCode: '68425' },
  { municipality: 'Málaga', department: 'Santander', daneCode: '68432' },
  { municipality: 'Matanza', department: 'Santander', daneCode: '68444' },
  { municipality: 'Mogotes', department: 'Santander', daneCode: '68464' },
  { municipality: 'Molagavita', department: 'Santander', daneCode: '68468' },
  { municipality: 'Ocamonte', department: 'Santander', daneCode: '68498' },
  { municipality: 'Oiba', department: 'Santander', daneCode: '68500' },
  { municipality: 'Onzaga', department: 'Santander', daneCode: '68502' },
  { municipality: 'Palmar', department: 'Santander', daneCode: '68522' },
  { municipality: 'Palmas del Socorro', department: 'Santander', daneCode: '68524' },
  { municipality: 'Páramo', department: 'Santander', daneCode: '68533' },
  { municipality: 'Piedecuesta', department: 'Santander', daneCode: '68547' },
  { municipality: 'Pinchote', department: 'Santander', daneCode: '68549' },
  { municipality: 'Puente Nacional', department: 'Santander', daneCode: '68572' },
  { municipality: 'Puerto Parra', department: 'Santander', daneCode: '68573' },
  { municipality: 'Puerto Wilches', department: 'Santander', daneCode: '68575' },
  { municipality: 'Rionegro', department: 'Santander', daneCode: '68615' },
  { municipality: 'Sabana de Torres', department: 'Santander', daneCode: '68655' },
  { municipality: 'San Andrés', department: 'Santander', daneCode: '68669' },
  { municipality: 'San Benito', department: 'Santander', daneCode: '68673' },
  { municipality: 'San Gil', department: 'Santander', daneCode: '68679' },
  { municipality: 'San Joaquín', department: 'Santander', daneCode: '68682' },
  { municipality: 'San José de Miranda', department: 'Santander', daneCode: '68684' },
  { municipality: 'San Miguel', department: 'Santander', daneCode: '68686' },
  { municipality: 'San Vicente de Chucurí', department: 'Santander', daneCode: '68689' },
  { municipality: 'Santa Bárbara', department: 'Santander', daneCode: '68705' },
  { municipality: 'Santa Helena del Opón', department: 'Santander', daneCode: '68720' },
  { municipality: 'Simacota', department: 'Santander', daneCode: '68745' },
  { municipality: 'Socorro', department: 'Santander', daneCode: '68755' },
  { municipality: 'Suaita', department: 'Santander', daneCode: '68770' },
  { municipality: 'Sucre', department: 'Santander', daneCode: '68773' },
  { municipality: 'Suratá', department: 'Santander', daneCode: '68780' },
  { municipality: 'Tona', department: 'Santander', daneCode: '68820' },
  { municipality: 'Valle de San José', department: 'Santander', daneCode: '68855' },
  { municipality: 'Vélez', department: 'Santander', daneCode: '68861' },
  { municipality: 'Vetas', department: 'Santander', daneCode: '68867' },
  { municipality: 'Villanueva', department: 'Santander', daneCode: '68872' },
  { municipality: 'Zapatoca', department: 'Santander', daneCode: '68895' },
  { municipality: 'Sincelejo', department: 'Sucre', daneCode: '70001' },
  { municipality: 'Buenavista', department: 'Sucre', daneCode: '70110' },
  { municipality: 'Caimito', department: 'Sucre', daneCode: '70124' },
  { municipality: 'Chalán', department: 'Sucre', daneCode: '70204' },
  { municipality: 'Coloso', department: 'Sucre', daneCode: '70215' },
  { municipality: 'Corozal', department: 'Sucre', daneCode: '70221' },
  { municipality: 'Coveñas', department: 'Sucre', daneCode: '70230' },
  { municipality: 'El Roble', department: 'Sucre', daneCode: '70233' },
  { municipality: 'Galeras', department: 'Sucre', daneCode: '70235' },
  { municipality: 'Guaranda', department: 'Sucre', daneCode: '70265' },
  { municipality: 'La Unión', department: 'Sucre', daneCode: '70400' },
  { municipality: 'Los Palmitos', department: 'Sucre', daneCode: '70418' },
  { municipality: 'Majagual', department: 'Sucre', daneCode: '70429' },
  { municipality: 'Morroa', department: 'Sucre', daneCode: '70473' },
  { municipality: 'Ovejas', department: 'Sucre', daneCode: '70508' },
  { municipality: 'Palmito', department: 'Sucre', daneCode: '70523' },
  { municipality: 'Sampués', department: 'Sucre', daneCode: '70670' },
  { municipality: 'San Benito Abad', department: 'Sucre', daneCode: '70678' },
  { municipality: 'San Juan de Betulia', department: 'Sucre', daneCode: '70702' },
  { municipality: 'San Marcos', department: 'Sucre', daneCode: '70708' },
  { municipality: 'San Onofre', department: 'Sucre', daneCode: '70713' },
  { municipality: 'San Pedro', department: 'Sucre', daneCode: '70717' },
  { municipality: 'Santiago de Tolú', department: 'Sucre', daneCode: '70820' },
  { municipality: 'Tolú', department: 'Sucre', daneCode: '70820' },
  { municipality: 'San Antonio de Palmito', department: 'Sucre', daneCode: '70523' },
  { municipality: 'Since', department: 'Sucre', daneCode: '70742' },
  { municipality: 'Sucre', department: 'Sucre', daneCode: '70771' },
  { municipality: 'Tolú Viejo', department: 'Sucre', daneCode: '70823' },
  { municipality: 'Ibagué', department: 'Tolima', daneCode: '73001' },
  { municipality: 'Alpujarra', department: 'Tolima', daneCode: '73024' },
  { municipality: 'Alvarado', department: 'Tolima', daneCode: '73026' },
  { municipality: 'Ambalema', department: 'Tolima', daneCode: '73030' },
  { municipality: 'Anzoátegui', department: 'Tolima', daneCode: '73043' },
  { municipality: 'Armero', department: 'Tolima', daneCode: '73055' },
  { municipality: 'Ataco', department: 'Tolima', daneCode: '73067' },
  { municipality: 'Cajamarca', department: 'Tolima', daneCode: '73124' },
  { municipality: 'Carmen de Apicalá', department: 'Tolima', daneCode: '73148' },
  { municipality: 'Casabianca', department: 'Tolima', daneCode: '73152' },
  { municipality: 'Chaparral', department: 'Tolima', daneCode: '73168' },
  { municipality: 'Coello', department: 'Tolima', daneCode: '73200' },
  { municipality: 'Coyaima', department: 'Tolima', daneCode: '73217' },
  { municipality: 'Cunday', department: 'Tolima', daneCode: '73226' },
  { municipality: 'Dolores', department: 'Tolima', daneCode: '73236' },
  { municipality: 'Espinal', department: 'Tolima', daneCode: '73268' },
  { municipality: 'Falan', department: 'Tolima', daneCode: '73270' },
  { municipality: 'Flandes', department: 'Tolima', daneCode: '73275' },
  { municipality: 'Fresno', department: 'Tolima', daneCode: '73283' },
  { municipality: 'Guamo', department: 'Tolima', daneCode: '73319' },
  { municipality: 'Herveo', department: 'Tolima', daneCode: '73347' },
  { municipality: 'Honda', department: 'Tolima', daneCode: '73349' },
  { municipality: 'Icononzo', department: 'Tolima', daneCode: '73352' },
  { municipality: 'Lérida', department: 'Tolima', daneCode: '73408' },
  { municipality: 'Líbano', department: 'Tolima', daneCode: '73411' },
  { municipality: 'Mariquita', department: 'Tolima', daneCode: '73443' },
  { municipality: 'Melgar', department: 'Tolima', daneCode: '73449' },
  { municipality: 'Murillo', department: 'Tolima', daneCode: '73461' },
  { municipality: 'Natagaima', department: 'Tolima', daneCode: '73483' },
  { municipality: 'Ortega', department: 'Tolima', daneCode: '73504' },
  { municipality: 'Palocabildo', department: 'Tolima', daneCode: '73520' },
  { municipality: 'Piedras', department: 'Tolima', daneCode: '73547' },
  { municipality: 'Planadas', department: 'Tolima', daneCode: '73555' },
  { municipality: 'Prado', department: 'Tolima', daneCode: '73563' },
  { municipality: 'Purificación', department: 'Tolima', daneCode: '73585' },
  { municipality: 'Rioblanco', department: 'Tolima', daneCode: '73616' },
  { municipality: 'Roncesvalles', department: 'Tolima', daneCode: '73622' },
  { municipality: 'Rovira', department: 'Tolima', daneCode: '73624' },
  { municipality: 'Saldaña', department: 'Tolima', daneCode: '73671' },
  { municipality: 'San Antonio', department: 'Tolima', daneCode: '73675' },
  { municipality: 'San Luis', department: 'Tolima', daneCode: '73678' },
  { municipality: 'Santa Isabel', department: 'Tolima', daneCode: '73686' },
  { municipality: 'Suárez', department: 'Tolima', daneCode: '73770' },
  { municipality: 'Valle de San Juan', department: 'Tolima', daneCode: '73854' },
  { municipality: 'Venadillo', department: 'Tolima', daneCode: '73861' },
  { municipality: 'Villahermosa', department: 'Tolima', daneCode: '73870' },
  { municipality: 'Villarrica', department: 'Tolima', daneCode: '73873' },
  { municipality: 'Cali', department: 'Valle del Cauca', daneCode: '76001' },
  { municipality: 'Santiago de Cali', department: 'Valle del Cauca', daneCode: '76001' },
  { municipality: 'Alcalá', department: 'Valle del Cauca', daneCode: '76020' },
  { municipality: 'Andalucía', department: 'Valle del Cauca', daneCode: '76036' },
  { municipality: 'Ansermanuevo', department: 'Valle del Cauca', daneCode: '76041' },
  { municipality: 'Argelia', department: 'Valle del Cauca', daneCode: '76054' },
  { municipality: 'Bolívar', department: 'Valle del Cauca', daneCode: '76100' },
  { municipality: 'Buenaventura', department: 'Valle del Cauca', daneCode: '76109' },
  { municipality: 'Buga', department: 'Valle del Cauca', daneCode: '76111' },
  { municipality: 'Guadalajara de Buga', department: 'Valle del Cauca', daneCode: '76111' },
  { municipality: 'Bugalagrande', department: 'Valle del Cauca', daneCode: '76113' },
  { municipality: 'Caicedonia', department: 'Valle del Cauca', daneCode: '76122' },
  { municipality: 'Calima', department: 'Valle del Cauca', daneCode: '76126' },
  { municipality: 'Candelaria', department: 'Valle del Cauca', daneCode: '76130' },
  { municipality: 'Cartago', department: 'Valle del Cauca', daneCode: '76147' },
  { municipality: 'Dagua', department: 'Valle del Cauca', daneCode: '76233' },
  { municipality: 'El Águila', department: 'Valle del Cauca', daneCode: '76243' },
  { municipality: 'El Cairo', department: 'Valle del Cauca', daneCode: '76246' },
  { municipality: 'El Cerrito', department: 'Valle del Cauca', daneCode: '76248' },
  { municipality: 'El Dovio', department: 'Valle del Cauca', daneCode: '76250' },
  { municipality: 'Florida', department: 'Valle del Cauca', daneCode: '76275' },
  { municipality: 'Ginebra', department: 'Valle del Cauca', daneCode: '76306' },
  { municipality: 'Guacarí', department: 'Valle del Cauca', daneCode: '76318' },
  { municipality: 'Jamundí', department: 'Valle del Cauca', daneCode: '76364' },
  { municipality: 'La Cumbre', department: 'Valle del Cauca', daneCode: '76377' },
  { municipality: 'La Unión', department: 'Valle del Cauca', daneCode: '76400' },
  { municipality: 'La Victoria', department: 'Valle del Cauca', daneCode: '76403' },
  { municipality: 'Obando', department: 'Valle del Cauca', daneCode: '76497' },
  { municipality: 'Palmira', department: 'Valle del Cauca', daneCode: '76520' },
  { municipality: 'Pradera', department: 'Valle del Cauca', daneCode: '76563' },
  { municipality: 'Restrepo', department: 'Valle del Cauca', daneCode: '76606' },
  { municipality: 'Riofrío', department: 'Valle del Cauca', daneCode: '76616' },
  { municipality: 'Roldanillo', department: 'Valle del Cauca', daneCode: '76622' },
  { municipality: 'San Pedro', department: 'Valle del Cauca', daneCode: '76670' },
  { municipality: 'Sevilla', department: 'Valle del Cauca', daneCode: '76736' },
  { municipality: 'Toro', department: 'Valle del Cauca', daneCode: '76823' },
  { municipality: 'Trujillo', department: 'Valle del Cauca', daneCode: '76828' },
  { municipality: 'Tuluá', department: 'Valle del Cauca', daneCode: '76834' },
  { municipality: 'Ulloa', department: 'Valle del Cauca', daneCode: '76845' },
  { municipality: 'Versalles', department: 'Valle del Cauca', daneCode: '76863' },
  { municipality: 'Vijes', department: 'Valle del Cauca', daneCode: '76869' },
  { municipality: 'Yotoco', department: 'Valle del Cauca', daneCode: '76890' },
  { municipality: 'Yumbo', department: 'Valle del Cauca', daneCode: '76892' },
  { municipality: 'Zarzal', department: 'Valle del Cauca', daneCode: '76895' },
  { municipality: 'Mitú', department: 'Vaupés', daneCode: '97001' },
  { municipality: 'Carurú', department: 'Vaupés', daneCode: '97161' },
  { municipality: 'Taraira', department: 'Vaupés', daneCode: '97666' },
  { municipality: 'Puerto Carreño', department: 'Vichada', daneCode: '99001' },
  { municipality: 'Cumaribo', department: 'Vichada', daneCode: '99773' },
  { municipality: 'La Primavera', department: 'Vichada', daneCode: '99524' },
  { municipality: 'Santa Rosalía', department: 'Vichada', daneCode: '99624' },
];

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[.,]/g, '')
    .trim();
}

/** Map from normalized municipality name to array of entries (handles duplicates across departments) */
export const DANE_CODES: Map<string, DaneEntry[]> = new Map();

for (const entry of DANE_ENTRIES) {
  const key = normalize(entry.municipality);
  const existing = DANE_CODES.get(key);
  if (existing) {
    existing.push(entry);
  } else {
    DANE_CODES.set(key, [entry]);
  }
}

// Aliases para nombres comunes que difieren del nombre oficial DANE.
// Sin esto, el fuzzy matching puede confundir municipios con nombres similares
// (ej: "Ubate" → "Sibate" porque tienen distancia Levenshtein = 2 y el nombre
// oficial "Villa de San Diego de Ubaté" queda muy lejos).
const MUNICIPALITY_ALIASES: Record<string, string> = {
  'ubate': 'villa de san diego de ubate',
  'ubaté': 'villa de san diego de ubate',
  'san diego de ubate': 'villa de san diego de ubate',
  'villa de ubate': 'villa de san diego de ubate',
};

for (const [alias, official] of Object.entries(MUNICIPALITY_ALIASES)) {
  const normalizedAlias = normalize(alias);
  const officialEntries = DANE_CODES.get(normalize(official));
  if (officialEntries && !DANE_CODES.has(normalizedAlias)) {
    DANE_CODES.set(normalizedAlias, officialEntries);
  }
}

function levenshtein(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;

  const dp: number[][] = Array.from({ length: m + 1 }, () => Array(n + 1).fill(0));

  for (let i = 0; i <= m; i++) dp[i][0] = i;
  for (let j = 0; j <= n; j++) dp[0][j] = j;

  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      dp[i][j] = Math.min(
        dp[i - 1][j] + 1,      // deletion
        dp[i][j - 1] + 1,      // insertion
        dp[i - 1][j - 1] + cost // substitution
      );
    }
  }

  return dp[m][n];
}

/**
 * Pad a 5-digit DANE code to the 8-digit format expected by Envia.com API.
 * Example: "11001" → "11001000", "05001" → "05001000"
 */
function padDaneCode(code: string): string {
  return code.length <= 5 ? code.padEnd(8, '0') : code;
}

/**
 * Look up a DANE code by city name, optionally filtering by department.
 * Uses exact match first, then fuzzy matching with Levenshtein distance <= 3.
 * Returns 8-digit DANE codes as required by Envia.com API.
 */
export function lookupDaneCode(
  city: string,
  department?: string,
): DaneLookupResult | null {
  const normalizedCity = normalize(city);

  // 1. Exact match
  const exactMatches = DANE_CODES.get(normalizedCity);
  if (exactMatches) {
    if (exactMatches.length === 1) {
      return { ...exactMatches[0], daneCode: padDaneCode(exactMatches[0].daneCode), source: 'exact' };
    }
    // Multiple matches — try to disambiguate with department
    if (department) {
      const normalizedDept = normalize(department);
      const deptMatch = exactMatches.find((e) => {
        const nd = normalize(e.department);
        return nd === normalizedDept || nd.includes(normalizedDept) || normalizedDept.includes(nd);
      });
      if (deptMatch) {
        return { ...deptMatch, daneCode: padDaneCode(deptMatch.daneCode), source: 'exact+department' };
      }
    }
    // Return first match if no department disambiguation possible
    return { ...exactMatches[0], daneCode: padDaneCode(exactMatches[0].daneCode), source: 'exact-first' };
  }

  // 2. Fuzzy match with dynamic threshold based on input length
  // Short inputs (e.g. "CC") get a tighter threshold to avoid absurd matches
  const maxDistance = Math.max(1, Math.min(3, Math.floor(normalizedCity.length * 0.4)));

  let bestDeptMatch: DaneEntry | null = null;
  let bestDeptDistance = maxDistance + 1;
  let bestAnyMatch: DaneEntry | null = null;
  let bestAnyDistance = maxDistance + 1;

  const normalizedDept = department ? normalize(department) : '';

  for (const [key, entries] of DANE_CODES) {
    const distance = levenshtein(normalizedCity, key);
    if (distance > maxDistance) continue;

    // Check for department match
    if (normalizedDept) {
      const deptMatch = entries.find((e) => {
        const nd = normalize(e.department);
        return nd === normalizedDept || nd.includes(normalizedDept) || normalizedDept.includes(nd);
      });
      if (deptMatch && distance < bestDeptDistance) {
        bestDeptDistance = distance;
        bestDeptMatch = deptMatch;
      }
    }

    if (distance < bestAnyDistance) {
      bestAnyDistance = distance;
      bestAnyMatch = entries[0];
    }
  }

  // Strongly prefer department-matching results; only fall back to any match
  // when no department was provided
  const finalMatch = bestDeptMatch || (normalizedDept ? null : bestAnyMatch);
  const finalDistance = bestDeptMatch ? bestDeptDistance : bestAnyDistance;

  if (finalMatch) {
    return { ...finalMatch, daneCode: padDaneCode(finalMatch.daneCode), source: `fuzzy-${finalDistance}` };
  }

  return null;
}
